export const EQUIPMENT_ITEM_TRASH_OPTIONS = [
  "SWEDISH SOLD",
  "EURO NCAP 5",
  "WHITE EXTERIOR COLOR",
  "SELECTION",
  "MOMENTUM",
  "PASSENGER DETECTOR FOR REAR SEAT",
  "SERVICE CONTRACT AVAILABLE",
  "SIDES",
  "FRONT FLOOR CHILD SEAT ANCHORS",
  "FUEL TANK",
  "FRONT AND REAR",
  "DELIVERY TO LOCATION",
  "CALL BEFORE COMMING",
  "SMART FINANCE",
  "ACTIVE",
  "REAR",
  "CARD FOR FUEL",
  "DYN EXTENSION",
  "FRONT",
  "FRONT: DRIVER",
  "FRONT: PASSENGER",
  "GRAY EXTERIOR COLOR",
  "HEAD",
  "KNEE",
  "LOW TAX",
  "ADDED VALUE CAMPAIGN",
  "NO EXPORT",
  "SIDE",
  "SILVER EXTERIOR COLOR",
  "WITHOUT HEAT ACCUMULATOR/EXTRA HEATER",
  "NO SMOKING VEHICLE",
];

export const EQUIPMENT_ITEM_GOOD_OPTIONS = [
  "12V SOCKET",
  "18 INCHES AMG WHEELS",
  "18 INCHES M SPORT WHEELS",
  "18 INCHES WHEELS",
  "18 INCHES WHEELS PERSEUS",
  "19 INCHES AMG WHEELS",
  "20 INCHES WHEELS VEGA",
  "360 DEGREE CAMERA",
  "7 SEATER",
  "7 SEATS",
  "ABS",
  "ACCELERATOR",
  "ACOUSTIC GLASS",
  "ACOUSTIC WINDOWS",
  "ACTIVE BRAKE ASSIST",
  "ACTIVE COURSE MANAGEMENT ASSISTANT",
  "ACTIVE GUARD PLUS",
  "ACTIVE INFO DISPLAY",
  "ACTIVE SAFETY BRAKE",
  "ADAPTIVE AIR SUSPENSION",
  "ADAPTIVE CHASSI",
  "ADAPTIVE CORNERING LIGHT",
  "ADAPTIVE CRUISE CONTROL",
  "ADAPTIVE LED HEADLIGHTS",
  "ADAPTIVE M SPORT SUSPENSION",
  "ADJUSTABLE STEERING WHEEL",
  "ADVANCED EXTERIOR",
  "AIRBAG",
  "AIRBAG COVER",
  "AIRBAG DISCONNECTION",
  "AIRBAG DRIVER",
  "AIRBAG DRIVER AND PASSENGER",
  "AIR CONDITIONING",
  "AIR CONDITIONING 2 ZONE",
  "AIR CONDITIONING 3 ZONE",
  "AIR CONDITIONING 4 ZONE",
  "AIR QUALITY SYSTEM",
  "AIR SUSPENSION",
  "AIR SUSPENSION ON REAR AXLE",
  "ALARM",
  "ALCOHOL LOCK PREP",
  "ALL SEASON TIRES",
  "ALL WHEEL DRIVE",
  "ALLOY WHEELS",
  "ALLWHEEL DRIVE",
  "ALPINE PACKAGE",
  "ALUMINIUM DECOR",
  "AMBIENT LIGHTING",
  "AMBIENT LIGHTNING",
  "AMG PERFORMANCE EXHAUST SYSTEM",
  "AMG SPORT",
  "ANDROID AUTO",
  "ANTI SKID SYSTEM",
  "APP-CONNECT",
  "APPLE CARPLAY",
  "APPLE CARPLAY AND ANDROID AUTO",
  "ARM REST",
  "ARMREST",
  "ASSISTANCE PACKAGE",
  "ASSISTANCE PACKAGE PLUS",
  "AUDI APPLICATION STORE",
  "AUDI CONNECT REMOTE & CONTROL",
  "AUDI DRIVE SELECT",
  "AUDI EXCLUSIVE SEAT BELTS",
  "AUDI PHONE BOX",
  "AUDI PRE SENSE FRONT",
  "AUDI PRE SENSE REAR PACKAGE",
  "AUDI SOUND SYSTEM",
  "AUDI VIRTUAL COCKPIT PLUS",
  "AUTO HOLD",
  "AUTOMAT",
  "AUTOMATIC BREAKING",
  "AUTOMATIC DIMMING REARVIEW MIRROR",
  "AUTOMATIC EMERGENCY BRAKE",
  "AUTOMATIC HEADLIGHT LEVELING",
  "AUTOMATIC HIGH BEAM",
  "AUTOMATIC LOCK",
  "AUTOMATIC SPORTS TRANSMISSION",
  "AUX INPUT",
  "BANG AND OLUFSEN SOUND SYSTEM",
  "BI-LED HEADLIGHTS",
  "BI-XENON HEADLIGHTS",
  "BLACK EXTERIOR COLOR",
  "BLACK GRILL",
  "BLACK HEADLINER",
  "BLACK INTERIOR",
  "BLACK OPTICS PACKAGE",
  "BLACK ROOF",
  "BLACK ROOF RAILS",
  "BLACK SIDE MIRRORS",
  "BLIND SPOT ASSISTANT",
  "BLIND SPOT MONITOR SYSTEM",
  "BLIND SPOT WARNING SYSTEM",
  "BLUETOOTH",
  "BOARD COMPUTER",
  "BOWERS AND WILKINS SOUND SYSTEM",
  "BRAKE ASSIST",
  "BREAKDOWN KIT",
  "BURMESTER SURROUND SOUND SYSTEM",
  "CABIN HEATER",
  "CARGO AREA BAG HOLDER",
  "CARE CONNECT",
  "CD PLAYER",
  "CD STEREO",
  "CENTER SCREEN",
  "CENTRAL LOCKING",
  "CENTRAL LOCKING (REMOTE CONTROLLED)",
  "CHARGING CABLE",
  "CHILD LOCK",
  "CITY ASSISTANCE PACKAGE",
  "CLIMATE CONTROL",
  "COLLISION WARNING SYSTEM",
  "COLOR MATCHED GRILL",
  "COLUMBUS NAVIGATION",
  "COMFORT FRONT SEATS",
  "COMFORT KEY",
  "COMFORT LEATHER SEATS",
  "COMFORT OPENING",
  "COMFORT PACKAGE",
  "COMFORT SEATS",
  "CONNECTED DRIVE SERVICES",
  "CONNECTED SAFETY",
  "COOLED GLOVE COMPARTMENT",
  "CORNERING LIGHT",
  "CORNERING LIGHT STATIC",
  "CROSS TRAFFIC ALERT",
  "CRUISE CONTROL",
  "CUSHION EXTENSION",
  "CUP HOLDER",
  "DAYTIME RUNNING LIGHT",
  "DEACTIVABLE PASSANGER AIRBAG",
  "DEACTIVATABLE PASSENGER AIRBAG",
  "DECORATIVE INSERTS",
  "DIESEL HEATER",
  "DIFFUSER IN HIGH GLOSS BLACK",
  "DIGITAL COCKPIT",
  "DIGITAL INSTRUMENT PANEL",
  "DIGITAL KEY",
  "DIGITAL LIGHT LOGO",
  "DIGITAL RADIO (DAB)",
  "DIMMING MIRRORS",
  "DISTANCE WARNING SYSTEM",
  "DRIVE MODE SELECTION",
  "DRIVER ASSISTANCE",
  "DRIVER AWARENESS",
  "DRIVER DISPLAY",
  "DRIVING ASSISTANT",
  "DRIVING ASSISTANT PLUS",
  "DYNAMIC CHASSIS CONTROL",
  "ELECTRIC CHARGING PORT",
  "ELECTRIC CLOCK",
  "ELECTRIC DRIVER SEAT",
  "ELECTRIC DRIVER SEAT WITH MEMORY",
  "ELECTRIC FOLDABLE SIDE MIRRORS",
  "ELECTRIC FRONT SEATS",
  "ELECTRIC FRONT SEATS WITH MEMORY",
  "ELECTRIC HEATER",
  "ELECTRIC PASSENGER SEAT",
  "ELECTRIC PASSENGER SEAT WITH MEMORY",
  "ELECTRIC REAR SEATS",
  "ELECTRIC SEATS",
  "ELECTRIC SEATS WITH MEMORY",
  "ELECTRIC SIDE MIRRORS",
  "ELECTRICALLY ADJUSTABLE LUMBAR SUPPORT 4 WAY",
  "ELECTRICALLY FOLDING REAR HEADRESTS",
  "ELECTRICALLY HEATED WINDSHIELD",
  "ELECTRONIC PARKING BRAKE",
  "EMERGENCY BRAKE",
  "EMERGENCY BRAKING SYSTEM",
  "EMERGENCY CALL",
  "EMERGENCY STOP ASSIST",
  "ENGINE HEATER",
  "ESP",
  "E-TRON SPORT SOUND",
  "EVOLUTION PACKAGE",
  "EXTERIOR SPEAKERS",
  "FABRIC SEATS",
  "FATIGUE WARNING",
  "FIRST AID CUSHION",
  "FLAT LOAD COMPARTMENT",
  "FLOOR MATS",
  "FOG LIGHTS",
  "FOLDING FRONT PASSENGER SEAT",
  "FOLDING REAR SEATS",
  "FORWARD COLLISION WARNING",
  "FRONT AND REAR SENSORS",
  "FRONT ASSIST",
  "FRONT FOG LIGHTS",
  "FRONT ISOFIX MOUNTS",
  "FRONT LUGGAGE COMPARTMENT",
  "FRONT PASSENGER AIRBAG",
  "FRONT SENSORS",
  "FRONT SPORT SEATS",
  "FULL BODY PAINT",
  "GEAR SHIFT PADDLES",
  "GLARE FREE HIGH BEAM",
  "GLOBAL OPEN/CLOSE WINDOWS",
  "GLOSS BLACK DECOR",
  "GOOGLE ASSISTANT",
  "GOOGLE MAPS",
  "GOOGLE PLAY STORE",
  "HANDSFREE POWER TAILGATE",
  "HANDS FREE",
  "HARMAN/KARDON",
  "HEAD RESTRAINTS",
  "HEAD UP DISPLAY",
  "HEADLIGHT WASHERS",
  "HEAT PUMP",
  "HEATED GRILLE EMBLEM",
  "HEATED SIDE MIRRORS",
  "HEATED STEERING WHEEL",
  "HEATED WINDSHIELD",
  "HEATED WINDSHIELD WASHERS",
  "HEATED WINDSHIELD WIPERS",
  "HI-FI SPEAKER SYSTEM",
  "HIGH BEAM ASSIST",
  "HILL DESCENT CONTROL",
  "HILL START ASSIST",
  "IMMOBILIZER",
  "INSTRUMENT PANEL",
  "INTEGRATED MUSIC STREAMING",
  "INTELLIGENT ACTIVE (IACC)",
  "INTELLIGENT SPEED ASSIST",
  "ISOFIX MOUNTS",
  "KEYLESS",
  "KEYLESS START",
  "LANE ASSIST",
  "LANE DEPARTURE ASSIST",
  "LASER LIGHT",
  "LEASABLE WITH VAT",
  "LEATHER STEERING WHEEL",
  "LEATHER UPHOLSTERY",
  "LED DAYTIME LIGHTS",
  "LED HEADLIGHTS",
  "LED REAR LIGHTS",
  "LED WARNING LIGHTS",
  "LIGHT SENSOR",
  "LIVE COCKPIT PLUS",
  "LOAD FLOOR FOLDING",
  "LOAD SHIFTING NET",
  "LOCKING BOLTS",
  "LTE SUPPORT",
  "LUMBAR SUPPORT",
  "M REAR SPOILER",
  "M SPORT ANTRACIT HEADLINER",
  "M SPORT STEERING WHEEL",
  "M SPORT SUSPENSION",
  "MASSAGE SEATS",
  "MATRIX LED HEADLIGHTS",
  "MBUX MULTIMEDIA SYSTEM",
  "MBUX NAVIGATION",
  "MERIDIAN SOUND SYSTEM",
  "METTALIC PAINT",
  "MMI EXPERIENCE PLUS",
  "MULTICOLOR LIGHTING PACKAGE",
  "MULTIFUNCTION SPORT STEERING WHEEL IN NAPPA LEATHER",
  "MULTIFUNCTIONAL STEERING WHEEL",
  "NAVIGATION",
  "NAVIGATION AMUNDSEN",
  "NEWLY SERVICED",
  "NO TAILPIPES",
  "OLED REAR LIGHTS",
  "ONCOMING MITIGATION",
  "ORREFORS GEAR SHIFTER",
  "OUTSIDE TEMPERATURE GAUGE",
  "PACKAGE: ADVANCED PLUS",
  "PACKAGE: ADVENTURE EDITION",
  "PACKAGE: AIR BALANCE PACKET",
  "PACKAGE: AMG",
  "PACKAGE: AMG LINE ADVANCED",
  "PACKAGE: AMG LINE PREMIUM",
  "PACKAGE: AVANTGARDE",
  "PACKAGE: BLACK OPTICS PACKAGE",
  "PACKAGE: BUSINESS PACKAGE",
  "PACKAGE: CLIMATE PACKAGE",
  "PACKAGE: COMFORT PACKAGE PLUS",
  "PACKAGE: COMFORT PACKAGE PRO",
  "PACKAGE: CONNECTED PACKAGE",
  "PACKAGE: CONNECTIVITY PACKAGE",
  "PACKAGE: EXECUTIVE",
  "PACKAGE: EXTENDED BLACK OPTICS PACKAGE",
  "PACKAGE: GLOSS BLACK SHADOWLINE",
  "PACKAGE: INTENSE",
  "PACKAGE: LIGHTING AND VISIBILITY PACKAGE",
  "PACKAGE: M AERODYNAMICS PACKAGE",
  "PACKAGE: M HIGH GLOSS PACKAGE",
  "PACKAGE: M SPORT",
  "PACKAGE: MEMORY PACKAGE",
  "PACKAGE: MIRROR PACKAGE",
  "PACKAGE: NIGHT PACKAGE",
  "PACKAGE: NIGHT PACKAGE 2",
  "PACKAGE: OFF ROAD TECHNICAL PACKAGE",
  "PACKAGE: PREMIUM PACKAGE",
  "PACKAGE: PREMIUM PACKAGE PLUS",
  "PACKAGE: PROLINE",
  "PACKAGE: QUATTRO EDITION",
  "PACKAGE: R DESIGN",
  "PACKAGE: R LINE",
  "PACKAGE: R LINE EXTERIOR",
  "PACKAGE: RS SPORT CHASSI WITH DYNAMIC RIDE",
  "PACKAGE: RS SPORT EXHAUST SYSTEM",
  "PACKAGE: S LINE",
  "PACKAGE: S LINE COMPETITION PLUS",
  "PACKAGE: S LINE INTERIOR",
  "PACKAGE: SLEEP PACKAGE",
  "PACKAGE: SPORT PACKAGE",
  "PACKAGE: ST LINE",
  "PACKAGE: STYLE",
  "PACKAGE: TECHNICAL PACKAGE",
  "PACKAGE: TOWING AND HEATER PACKAGE",
  "PACKAGE: TOWING AND HEATER PACKAGE BUSINESS",
  "PACKAGE: WINTER PACKAGE",
  "PANEL LIGHTING",
  "PANO",
  "PARCEL SHELF",
  "PARK ASSIST",
  "PARK ASSIST WITH REAR CAMERA",
  "PARKING HEATER",
  "PARTICLE FILTER",
  "PASSENGER DISPLAY",
  "PEDALS IN STAINLESS STEEL",
  "PEDESTRIAN DETECTION",
  "PEUGEOT CONNECT",
  "PILLOWS",
  "PILOT ASSIST",
  "PIXEL LED HEADLIGHTS",
  "POWER STEERING",
  "POWER TAILGATE",
  "POWER WINDOWS",
  "POWER WINDOWS (FRONT AND REAR)",
  "POWER WINDOWS (FRONT)",
  "POWER WINDOWS (REAR)",
  "PRE-CONDITIONING",
  "PREMIUM SOUND SYSTEM",
  "PREPARATION FOR NAVIGATION",
  "PROGRESSIVE POWER STEERING",
  "QUATTRO EDITION",
  "RADIO",
  "RAIN SENSOR",
  "READYTODRIVE NOTIFICATION",
  "READING LAMP",
  "REAR CAMERA",
  "REAR CLIMATE PANEL",
  "REAR COLLISION MITIGATION",
  "REAR COLLISION WARNING",
  "REAR ISOFIX MOUNTS",
  "REAR SENSORS",
  "REAR SUN BLINDS",
  "REAR TRAFFIC ALERT",
  "REARVIEW MIRROR",
  "RED BRAKE CALIPERS",
  "RED EXTERIOR COLOR",
  "ROOF RAILS",
  "RUBBER MATS",
  "RUN OFF ROAD MITIGATION",
  "SAFETY ASSISTANCE",
  "SEAT HEATING",
  "SEAT HEATING (FRONT AND REAR)",
  "SEAT HEATING (FRONT)",
  "SEAT HEATING (REAR)",
  "SEAT VENTILATION",
  "SEAT VENTILATION (FRONT)",
  "SECURITY LIGHTING",
  "SENSOR (FRONT AND REAR)",
  "SENSOR (FRONT)",
  "SENSOR (REAR)",
  "SENSORS (FRONT AND REAR)",
  "SENSORS (FRONT)",
  "SIDE ASSIST",
  "SIDE MIRRORS",
  "SIDE WINDOW TRIM/BLACK",
  "SIDEAIRBAGS",
  "SIGNAGE SCANNING",
  "SILVER GRILL",
  "SILVER ROOF RAILS",
  "SMARPHONE INTERFACE",
  "SMART LIGHT ASSIST",
  "SMARTPHONE",
  "SMARTPHONE INTEGRATION",
  "SMOKING PACKAGE",
  "SOFT CLOSE",
  "SOS",
  "SOUND SYSTEM",
  "SPARE WHEEL",
  "SPEED LIMITER",
  "SPLIT REAR SEAT",
  "SPORT CHASSI",
  "SPORT SEATS",
  "SPORT STEERING WHEEL",
  "SPORTS STEERING WHEEL",
  "S-SPORT SEATS",
  "STABILITY CONTROL",
  "STANDARD EQUIPEMENT",
  "START/STOP FUNCTION",
  "STEERING WHEEL KNOBS",
  "STEERING WHEELS BUTTONS IN HB BLACK",
  "STEREO",
  "STORAGE PACKAGE",
  "STUDDED WINTER TIRES",
  "SUN BLINDS",
  "SUMMER AND WINTER WHEELS",
  "SUMMER TIRES",
  "SUMMER WHEELS",
  "SUNSHADING GLASS",
  "TECH PLUS",
  "THEFT ALARM",
  "TINTED CARGO SPACE",
  "TINTED WINDOWS",
  "TIRE PRESSURE CONTROL",
  "TIRE REPAIR KIT",
  "TIRE STORAGE",
  "TOW HOOK",
  "TOYOTA SAFETY SENSE",
  "TOYOTA SMART CONNECT",
  "TOYOTA SMART MULTIMEDIA",
  "TRACTION CONTROL",
  "TRACTION CONTROL SYSTEM",
  "TRAFFIC SIGN RECOGNITION",
  "TRAILER ASSIST",
  "TRAILER ASSISTANT",
  "TRIP COMPUTER",
  "TRUNK CARPET",
  "TV",
  "UPHOLSTERY (ALCANTARA AND SENSATEC)",
  "UPHOLSTERY (ALCANTARA)",
  "UPHOLSTERY (ARTIFICIAL LEATHER ARTICO AND MICROFIBER)",
  "UPHOLSTERY (BLACK LEATHERETTE AND FABRIC)",
  "UPHOLSTERY (FABRIC)",
  "UPHOLSTERY (HALF LEATHER)",
  "UPHOLSTERY (LEATHER AND ALCANATARA)",
  "UPHOLSTERY (LEATHER AND ALCANTARA)",
  "UPHOLSTERY (LEATHER AND FABRIC)",
  "UPHOLSTERY (LEATHERETTE AND FABRIC)",
  "UPHOLSTERY (VALCONA LEATHER WITH DIAMOND QUILTING)",
  "UPHOLSTERY PREMIUM FABRIC AND SUEDE",
  "UPHOLSTERY: (VALCONA LEATHER WITH DIAMOND QUILTING)",
  "USB SOCKET TYPE C",
  "USB SOCKETS",
  "USB SOCKETS TYPE C",
  "VARIABLE SPORTS STEERING",
  "VEHICLE PROTECTION COVER",
  "VELOUR FLOOR MATS",
  "VISIBILITY PROTECTION",
  "VOICE CONTROL",
  "VOLVO ON CALL",
  "WIDESCREEN DISPLAY",
  "WIFI HOTSPOT",
  "WINDSHIELD WIPERS WITH WASHERS",
  "WINTER TIRES",
  "WINTER WHEELS",
  "WIRELESS PHONE CHARGER",
  "WITHOUT MODEL AND ENGINE DESIGNATION EMBLEM",
  "XENON (HIGH BEAM)",
  "XENON (LOW BEAM)",
  "XENON LIGHTS",
  "ALCANTARA SEATS",
  "LEATHER SEATS",
  "PART-LEATHER SEATS",
];

export const EQUIPMENT_ITEM_OPTIONS = [
  ...EQUIPMENT_ITEM_GOOD_OPTIONS,
  ...EQUIPMENT_ITEM_TRASH_OPTIONS,
];

export const BODY_TYPE_OPTIONS = [
  "SUV",
  "HATCHBACK",
  "COMBI",
  "SEDAN",
  "COMMERCIAL VEHICLE",
  "MINI VAN",
  "COUPE",
  "CABRIOLET",
];

export const FUEL_TYPE_OPTIONS = [
  "BENZIN",
  "DIESEL",
  "HYBRID",
  "ELECTRIC",
  "BENZIN/ETHANOL",
  "NATURAL GAS",
  "BENZIN/NATURAL GAS",
];

export const DRIVE_TYPE_OPTIONS = ["2WHEELDRIVE", "ALLWHEELDRIVE"];

export const TRANSMISSION_TYPE_OPTIONS = ["AUTOMATIC", "MANUAL"];

export const COLOR_OPTIONS = [
  "WHITE",
  "BLACK",
  "GRAY",
  "SILVER",
  "BLUE",
  "RED",
  "GREEN",
  "BROWN",
  "PURPLE",
  "ORANGE",
];

export const INTERIOR_MATERIAL_OPTIONS = [
  "LEATHER",
  "ALCANTARA",
  "PART-LEATHER",
  "FABRIC",
];

export const BRAND_OPTIONS = [
  "AUDI",
  "VOLKSWAGEN",
  "VOLVO",
  "TOYOTA",
  "MERCEDES-BENZ",
  "BMW",
  "KIA",
  "CITROEN",
  "SKODA",
  "OPEL",
  "FORD",
  "JAGUAR",
  "HYUNDAI",
  "HONDA",
  "MAZDA",
  "RENAULT",
  "PEUGEOT",
  "CUPRA",
  "MG",
  "ALFA ROMEO",
  "SEAT",
  "FIAT",
  "SUZUKI",
  "LEXUS",
  "LYNK-AND-CO",
  "SUBARU",
  "MITSUBISHI",
  "CHEVROLET",
  "MINI",
  "SAAB",
  "TESLA",
  "NISSAN",
  "DACIA",
  "PORSCHE",
  "LAND ROVER",
  "DODGE",
];

export const ENERGY_EFFICIENCY_OPTIONS = ["A", "B", "C", "D", "E", "F", "G"];

export const EURO_NORM_OPTIONS = ["EURO 6", "EURO 5", "EURO 4"];

export const CURRENCY_OPTIONS = ["EUR", "CHF", "SEK"];

export const MODEL_OPTIONS = {
  "MERCEDES-BENZ": [
    "190",
    "200",
    "220",
    "230",
    "240",
    "250",
    "260",
    "270",
    "280",
    "290",
    "300",
    "320",
    "350",
    "380",
    "400",
    "416",
    "420",
    "450",
    "500",
    "560",
    "600",
    "CITAN",
    "EQA",
    "EQB",
    "EQC",
    "EQE",
    "EQS",
    "EQT",
    "EQV",
    "ESPRINTER",
    "EVITO",
    "MB 100",
    "SLR",
    "SLS AMG",
    "SPRINTER",
    "T-CLASS",
    "VANEO",
    "VARIO",
    "VIANO",
    "VITO",
    "A 140",
    "A 150",
    "A 160",
    "A 170",
    "A 180",
    "A 190",
    "A 200",
    "A 210",
    "A 220",
    "A 250",
    "A 35 AMG",
    "A 45 AMG",
    "B 150",
    "B 160",
    "B 170",
    "B 180",
    "B 200",
    "B 220",
    "B 250",
    "B ELECTRIC DRIVE",
    "CE 200",
    "CE 220",
    "CE 230",
    "CE 280",
    "CE 300",
    "CE 320",
    "C 160",
    "C 180",
    "C 200",
    "C 220",
    "C 230",
    "C 240",
    "C 250",
    "C 270",
    "C 280",
    "C 300",
    "C 30 AMG",
    "C 320",
    "C 32 AMG",
    "C 350",
    "C 36 AMG",
    "C 400",
    "C 43 AMG",
    "C 450 AMG",
    "C 55 AMG",
    "C 63 AMG",
    "CLA 180",
    "CLA 180 SHOOTING BRAKE",
    "CLA 200",
    "CLA 200 SHOOTING BRAKE",
    "CLA 220",
    "CLA 220 SHOOTING BRAKE",
    "CLA 250",
    "CLA 250 SHOOTING BRAKE",
    "CLA 35 AMG",
    "CLA 45 AMG",
    "CLS 220",
    "CLS 250",
    "CLS 300",
    "CLS 320",
    "CLS 350",
    "CLS 400",
    "CLS 500",
    "CLS 55 AMG",
    "CLS 63 AMG",
    "E 200",
    "E 220",
    "E 250",
    "E 280",
    "E 300",
    "E 320",
    "E 350",
    "E 400",
    "E 500",
    "E 55 AMG",
    "E 63 AMG",
    "G 300",
    "G 350",
    "G 400",
    "G 500",
    "G 55 AMG",
    "G 63 AMG",
    "GLA 180",
    "GLA 200",
    "GLA 220",
    "GLA 250",
    "GLA 35 AMG",
    "GLA 45 AMG",
    "GLB 200",
    "GLB 220",
    "GLB 250",
    "GLB 35 AMG",
    "GLC 200",
    "GLC 220",
    "GLC 250",
    "GLC 300",
    "GLC 350",
    "GLC 400",
    "GLC 43 AMG",
    "GLC 450",
    "GLC 63 AMG",
    "GLE 250",
    "GLE 300",
    "GLE 350",
    "GLE 400",
    "GLE 500",
    "GLE 53 AMG",
    "GLE 63 AMG",
    "GLK 200",
    "GLK 220",
    "GLK 250",
    "GLK 300",
    "GLK 320",
    "GLK 350",
    "GLS 350",
    "GLS 400",
    "GLS 500",
    "GLS 600",
    "GLS 63 AMG",
    "S 300",
    "S 350",
    "S 400",
    "S 450",
    "S 500",
    "S 550",
    "S 600",
    "S 63 AMG",
    "S 65 AMG",
    "SL 300",
    "SL 350",
    "SL 400",
    "SL 500",
    "SL 55 AMG",
    "SL 63 AMG",
    "SLK 200",
    "SLK 230",
    "SLK 250",
    "SLK 280",
    "SLK 300",
    "SLK 320",
    "SLK 350",
    "SLK 55 AMG",
    "SLK 63 AMG",
    "V 200",
    "V 220",
    "V 230",
    "V 250",
    "V 280",
    "V 300",
    "V 350",
    "V 400",
    "V 500",
    "V 600",
    "V 63 AMG",
    "X 220",
    "X 250",
    "X 350",
  ],
  BMW: [
    "2002",
    "840",
    "850",
    "I3",
    "I4",
    "I5",
    "I7",
    "I8",
    "IX",
    "IX1",
    "IX2",
    "IX3",
    "114",
    "116",
    "118",
    "120",
    "123",
    "125",
    "128",
    "130",
    "135",
    "1 M COUPE",
    "214 ACTIVE TOURER",
    "214 GRAN TOURER",
    "216",
    "216 ACTIVE TOURER",
    "216 GRAN COUPE",
    "216 GRAN TOURER",
    "218",
    "218 ACTIVE TOURER",
    "218 GRAN COUPE",
    "218 GRAN TOURER",
    "220",
    "220 ACTIVE TOURER",
    "220 GRAN COUPE",
    "220 GRAN TOURER",
    "223 ACTIVE TOURER",
    "225",
    "225 ACTIVE TOURER",
    "228",
    "230",
    "2 SERIES GRAN COUPE",
    "315",
    "316",
    "318",
    "318 GRAN TURISMO",
    "320",
    "320 GRAN TURISMO",
    "323",
    "324",
    "325",
    "325 GRAN TURISMO",
    "328",
    "328 GRAN TURISMO",
    "330",
    "330 GRAN TURISMO",
    "335",
    "335 GRAN TURISMO",
    "340",
    "340 GRAN TURISMO",
    "ACTIVEHYBRID 3",
    "418",
    "418 GRAN COUPE",
    "420",
    "420 GRAN COUPE",
    "425",
    "425 GRAN COUPE",
    "428",
    "428 GRAN COUPE",
    "430",
    "430 GRAN COUPE",
    "435",
    "435 GRAN COUPE",
    "440",
    "440 GRAN COUPE",
    "518",
    "520",
    "520 GRAN TURISMO",
    "523",
    "524",
    "525",
    "528",
    "530",
    "530 GRAN TURISMO",
    "535",
    "535 GRAN TURISMO",
    "540",
    "545",
    "550",
    "550 GRAN TURISMO",
    "ACTIVEHYBRID 5",
    "620 GRAN TURISMO",
    "628",
    "630",
    "630 GRAN TURISMO",
    "633",
    "635",
    "640",
    "640 GRAN COUPE",
    "640 GRAN TURISMO",
    "645",
    "650",
    "650 GRAN COUPE",
    "725",
    "728",
    "730",
    "732",
    "735",
    "740",
    "745",
    "750",
    "760",
    "ACTIVEHYBRID 7",
    "M135",
    "M140I",
    "M2",
    "M235",
    "M240I",
    "M3",
    "M340D",
    "M340I",
    "M4",
    "M440",
    "M5",
    "M550",
    "M6",
    "M760",
    "M8",
    "M850",
    "ACTIVEHYBRID X6",
    "X1",
    "X2",
    "X3",
    "X3 M",
    "X3 M40",
    "X3 M50",
    "X4",
    "X4 M",
    "X4 M40",
    "X5",
    "X5 M",
    "X5 M50",
    "X5 M60",
    "X6",
    "X6 M",
    "X6 M50",
    "X6 M60",
    "X7",
    "X7 M50",
    "X7 M60",
    "XM",
    "Z1",
    "Z3",
    "Z3 M",
    "Z4",
    "Z4 M",
    "Z4 M40I",
    "Z8",
  ],
  AUDI: [
    "100",
    "200",
    "80",
    "90",
    "A1",
    "A2",
    "A3",
    "A4",
    "A4 ALLROAD",
    "A5",
    "A6",
    "A6 ALLROAD",
    "A6 E-TRON",
    "A7",
    "A8",
    "CABRIOLET",
    "COUPE",
    "E-TRON",
    "E-TRON GT",
    "Q2",
    "Q3",
    "Q4",
    "Q4 E-TRON",
    "Q5",
    "Q6 E-TRON",
    "Q7",
    "Q8",
    "Q8 E-TRON",
    "QUATTRO",
    "R8",
    "RS2",
    "RS3",
    "RS4",
    "RS5",
    "RS6",
    "RS7",
    "RS E-TRON GT",
    "RSQ3",
    "RSQ8",
    "S1",
    "S2",
    "S3",
    "S4",
    "S5",
    "S6",
    "S6 E-TRON",
    "S7",
    "S8",
    "SQ2",
    "SQ5",
    "SQ6 E-TRON",
    "SQ7",
    "SQ8",
    "SQ8 E-TRON",
    "V8",
    "TT",
    "TT RS",
    "TTS",
  ],
  VOLKSWAGEN: [
    "181",
    "AMAROK",
    "ARTEON",
    "BEETLE",
    "BORA",
    "BUGGY",
    "CADDY",
    "CADDY MAXI",
    "CC",
    "CORRADO",
    "CRAFTER",
    "EOS",
    "E-UP!",
    "FOX",
    "ID.3",
    "ID.4",
    "ID.5",
    "ID.6",
    "ID.7",
    "ID. BUZZ",
    "ILTIS",
    "JETTA",
    "KÄFER",
    "KARMANN GHIA",
    "LT",
    "LUPO",
    "NEW BEETLE",
    "PHAETON",
    "POLO",
    "ROUTAN",
    "SANTANA",
    "SCIROCCO",
    "SHARAN",
    "T1",
    "T2",
    "TAIGO",
    "TARO",
    "TAYRON",
    "T-CROSS",
    "TIGUAN",
    "TIGUAN ALLSPACE",
    "TOUAREG",
    "TOURAN",
    "T-ROC",
    "UP!",
    "VENTO",
    "XL1",
    "GOLF",
    "GOLF PLUS",
    "GOLF SPORTSVAN",
    "PASSAT",
    "PASSAT ALLTRACK",
    "PASSAT CC",
    "PASSAT VARIANT",
    "T3 OTHER",
    "T3 CARAVELLE",
    "T3 KOMBI",
    "T3 MULTIVAN",
    "T4 OTHER",
    "T4 CALIFORNIA",
    "T4 CARAVELLE",
    "T4 KOMBI",
    "T4 MULTIVAN",
    "T5 OTHER",
    "T5 CALIFORNIA",
    "T5 CARAVELLE",
    "T5 KOMBI",
    "T5 MULTIVAN",
    "T5 SHUTTLE",
    "T5 TRANSPORTER",
    "T6 OTHER",
    "T6 CALIFORNIA",
    "T6 CARAVELLE",
    "T6 KOMBI",
    "T6 MULTIVAN",
    "T6 TRANSPORTER",
    "T7 CALIFORNIA",
    "T7 CARAVELLE",
    "T7 KOMBI",
    "T7 MULTIVAN",
    "T7 OTHER",
    "T7 TRANSPORTER",
  ],
  PORSCHE: [
    "356",
    "912",
    "914",
    "918",
    "924",
    "928",
    "944",
    "959",
    "962",
    "968",
    "BOXSTER",
    "CARRERA GT",
    "CAYENNE",
    "CAYMAN",
    "MACAN",
    "PANAMERA",
    "TAYCAN",
    "911 URMODELL",
    "930",
    "964",
    "991",
    "992",
    "993",
    "996",
    "997",
  ],
  FORD: [
    "AEROSTAR",
    "B-MAX",
    "BRONCO",
    "BRONCO SPORT",
    "CAPRI",
    "C-MAX",
    "COUGAR",
    "COURIER",
    "CROWN",
    "ECONOLINE",
    "ECONOVAN",
    "ECOSPORT",
    "EDGE",
    "ESCAPE",
    "ESCORT",
    "EXCURSION",
    "EXPEDITION",
    "EXPLORER",
    "EXPRESS",
    "F 100",
    "F 150",
    "F 250",
    "F 350",
    "FAIRLANE",
    "FALCON",
    "FIESTA",
    "FLEX",
    "FOCUS",
    "FUSION",
    "GALAXY",
    "GRANADA",
    "GRAND C-MAX",
    "GRAND TOURNEO",
    "GT",
    "KA/KA+",
    "KUGA",
    "MAVERICK",
    "MERCURY",
    "MONDEO",
    "MUSTANG",
    "MUSTANG MACH-E",
    "ORION",
    "PROBE",
    "PUMA",
    "PUMA GEN-E",
    "RANGER",
    "RAPTOR",
    "SCORPIO",
    "SIERRA",
    "S-MAX",
    "SPORTKA",
    "STREETKA",
    "TAUNUS",
    "TAURUS",
    "THUNDERBIRD",
    "WINDSTAR",
    "TOURNEO",
    "TOURNEO CONNECT",
    "TOURNEO COURIER",
    "TOURNEO CUSTOM",
    "TRANSIT",
    "TRANSIT CONNECT",
    "TRANSIT COURIER",
    "TRANSIT CUSTOM",
  ],
  SKODA: [
    "105",
    "120",
    "130",
    "135",
    "CITIGO",
    "ELROQ",
    "ENYAQ",
    "FABIA",
    "FAVORIT",
    "FELICIA",
    "FORMAN",
    "KAMIQ",
    "KAROQ",
    "KODIAQ",
    "OCTAVIA",
    "PICK-UP",
    "PRAKTIK",
    "RAPID",
    "ROOMSTER",
    "SCALA",
    "SUPERB",
    "YETI",
  ],
  OPEL: [
    "ADAM",
    "AGILA",
    "AMPERA",
    "AMPERA-E",
    "ANTARA",
    "ARENA",
    "ASCONA",
    "ASTRA",
    "ASTRA ELECTRIC",
    "CALIBRA",
    "CAMPO",
    "CASCADA",
    "CAVALIER",
    "COMBO",
    "COMBO ELECTRIC",
    "COMBO LIFE",
    "COMMODORE",
    "CORSA",
    "CROSSLAND (X)",
    "DIPLOMAT",
    "FRONTERA",
    "GRANDLAND (X)",
    "GT",
    "INSIGNIA",
    "INSIGNIA CT",
    "KADETT",
    "KARL",
    "MANTA",
    "MERIVA",
    "MOKKA",
    "MOKKA-E",
    "MOKKA X",
    "MONTEREY",
    "MONZA",
    "MOVANO",
    "NOVA",
    "OMEGA",
    "PICK UP SPORTSCAP",
    "REKORD",
    "ROCKS-E",
    "SENATOR",
    "SIGNUM",
    "SINTRA",
    "SPEEDSTER",
    "TIGRA",
    "VECTRA",
    "VIVARO",
    "ZAFIRA",
    "ZAFIRA ELECTRIC",
    "ZAFIRA LIFE",
    "ZAFIRA TOURER",
  ],
  TOYOTA: [
    "4-RUNNER",
    "ALPHARD",
    "AURIS",
    "AURIS TOURING SPORTS",
    "AVALON",
    "AVENSIS",
    "AVENSIS VERSO",
    "AYGO (X)",
    "BZ4X",
    "CAMRY",
    "CARINA",
    "CELICA",
    "C-HR",
    "COROLLA",
    "COROLLA CROSS",
    "COROLLA VERSO",
    "CRESSIDA",
    "CROWN",
    "DYNA",
    "FCV",
    "FJ",
    "FORTUNER",
    "GR86",
    "GT86",
    "HIACE",
    "HIGHLANDER",
    "HILUX",
    "IQ",
    "LAND CRUISER",
    "LITE-ACE",
    "MATRIX",
    "MIRAI",
    "MR 2",
    "PASEO",
    "PICNIC",
    "PREVIA",
    "PRIUS",
    "PRIUS+",
    "PROACE (VERSO)",
    "PROACE CITY",
    "PROACE MAX",
    "PROACE VERSO ELECTRIC",
    "RAV 4",
    "SEQUOIA",
    "SIENNA",
    "STARLET",
    "SUPRA",
    "TACOMA",
    "TERCEL",
    "TUNDRA",
    "URBAN CRUISER",
    "VERSO",
    "VERSO-S",
    "YARIS",
    "YARIS CROSS",
  ],
  VOLVO: [
    "240",
    "244",
    "245",
    "262",
    "264",
    "340",
    "360",
    "440",
    "460",
    "480",
    "740",
    "744",
    "745",
    "760",
    "780",
    "850",
    "855",
    "940",
    "944",
    "945",
    "960",
    "965",
    "AMAZON",
    "C30",
    "C40",
    "C70",
    "EC40",
    "ES90",
    "EX30",
    "EX40",
    "EX90",
    "POLAR",
    "S40",
    "S60",
    "S60 CROSS COUNTRY",
    "S70",
    "S80",
    "S90",
    "V40",
    "V40 CROSS COUNTRY",
    "V50",
    "V60",
    "V60 CROSS COUNTRY",
    "V70",
    "V90",
    "V90 CROSS COUNTRY",
    "XC40",
    "XC60",
    "XC70",
    "XC90",
  ],
  ABARTH: [
    "124 SPIDER",
    "500",
    "500C",
    "595",
    "595C",
    "595 COMPETIZIONE",
    "595 TURISMO",
    "600E",
    "695",
    "695C",
    "GRANDE PUNTO",
    "PUNTO EVO",
  ],
  "ALFA ROMEO": [
    "145",
    "146",
    "147",
    "155",
    "156",
    "159",
    "164",
    "166",
    "33",
    "4C",
    "75",
    "8C",
    "90",
    "ALFASUD",
    "ALFETTA",
    "BRERA",
    "CROSSWAGON",
    "GIULIA",
    "GIULIETTA",
    "GT",
    "GTV",
    "JUNIOR",
    "MITO",
    "SPIDER",
    "SPRINT",
    "STELVIO",
    "TONALE",
  ],
  ALPINA: [
    "B10",
    "B12",
    "B3",
    "B4",
    "B5",
    "B6",
    "B7",
    "B8",
    "D10",
    "D3",
    "D3 S",
    "D4",
    "D4 S",
    "D5",
    "ROADSTER S",
    "XB7",
    "XD3",
    "XD4",
  ],
  ALPINE: ["A110", "A290"],
  "ASIA-MOTORS": ["ROCSTA"],
  "ASTON-MARTIN": [
    "AR1",
    "CYGNET",
    "DB",
    "DB11",
    "DB12",
    "DB7",
    "DB9",
    "DBS",
    "DBX",
    "LAGONDA",
    "RAPIDE",
    "V12 VANTAGE",
    "V8 VANTAGE",
    "VANQUISH",
    "VIRAGE",
  ],
  BENTLEY: [
    "ARNAGE",
    "AZURE",
    "BENTAYGA",
    "BROOKLANDS",
    "EIGHT",
    "FLYING SPUR",
    "MULSANNE",
    "S2",
    "TURBO R",
    "TURBO RT",
    "TURBO S",
    "CONTINENTAL",
    "CONTINENTAL FLYING SPUR",
    "CONTINENTAL GT",
    "CONTINENTAL GTC",
    "CONTINENTAL SUPERSPORTS",
  ],
  BUGATTI: ["CHIRON", "EB 110", "VEYRON"],
  BYD: [
    "ATTO 2",
    "ATTO 3",
    "DOLPHIN",
    "ETP 3",
    "HAN",
    "SEAL",
    "SEALION 7",
    "SEAL U",
    "TANG",
  ],
  CADILLAC: [
    "ALLANTE",
    "ATS",
    "BLS",
    "CT5",
    "CT6",
    "CTS",
    "DEVILLE",
    "ELDORADO",
    "ESCALADE",
    "FLEETWOOD",
    "SEVILLE",
    "SRX",
    "STS",
    "XLR",
    "XT4",
    "XT5",
    "XT6",
  ],
  CHRYSLER: [
    "200",
    "300C",
    "300 M",
    "ASPEN",
    "CROSSFIRE",
    "DAYTONA",
    "ES",
    "GRAND VOYAGER",
    "GS",
    "GTS",
    "IMPERIAL",
    "LE BARON",
    "NEON",
    "NEW YORKER",
    "PACIFICA",
    "PT CRUISER",
    "SARATOGA",
    "SEBRING",
    "STRATUS",
    "VALIANT",
    "VIPER",
    "VISION",
    "VOYAGER",
  ],
  CITROEN: [
    "2 CV",
    "AMI",
    "AX",
    "BERLINGO",
    "BX",
    "C1",
    "C2",
    "C3",
    "C3 AIRCROSS",
    "C3 PICASSO",
    "C4",
    "C4 AIRCROSS",
    "C4 CACTUS",
    "C4 PICASSO",
    "C4 SPACETOURER",
    "C4 X",
    "C5",
    "C5 AIRCROSS",
    "C5 X",
    "C6",
    "C8",
    "C-CROSSER",
    "C-ELYSEE",
    "CX",
    "C-ZERO",
    "DS",
    "DS3",
    "DS4",
    "DS4 CROSSBACK",
    "DS5",
    "E-BERLINGO",
    "E-C3",
    "E-C3 AIRCROSS",
    "E-C4",
    "E-C4 X",
    "E-MEHARI",
    "E-SPACETOURER",
    "EVASION",
    "GRAND C4 PICASSO / SPACETOURER",
    "GSA",
    "JUMPER",
    "JUMPY",
    "NEMO",
    "SAXO",
    "SM",
    "SPACETOURER",
    "VISA",
    "XANTIA",
    "XM",
    "XSARA",
    "XSARA PICASSO",
    "ZX",
  ],
  CORVETTE: ["C1", "C2", "C3", "C4", "C5", "C6", "C7", "C8", "Z06", "ZR 1"],
  CUPRA: [
    "ARONA",
    "ATECA",
    "BORN",
    "FORMENTOR",
    "IBIZA",
    "LEON",
    "TAVASCAN",
    "TERRAMAR",
  ],
  DACIA: [
    "BIGSTER",
    "DOKKER",
    "DUSTER",
    "JOGGER",
    "LODGY",
    "LOGAN",
    "LOGAN PICK-UP",
    "PICK UP",
    "SANDERO",
    "SPRING",
  ],
  DODGE: [
    "AVENGER",
    "CALIBER",
    "CHALLENGER",
    "CHARGER",
    "CORONET",
    "DAKOTA",
    "DART",
    "DEMON",
    "DURANGO",
    "GRAND CARAVAN",
    "HORNET",
    "JOURNEY",
    "MAGNUM",
    "NEON",
    "NITRO",
    "RAM",
    "STEALTH",
    "VIPER",
  ],
  FERRARI: [
    "208",
    "246",
    "250",
    "275",
    "288",
    "296 GTB",
    "296 GTS",
    "308",
    "328",
    "330",
    "348",
    "360",
    "365",
    "400",
    "412",
    "456",
    "458",
    "488 GTB",
    "488 PISTA",
    "488 SPIDER",
    "512",
    "550",
    "575",
    "599 GTB",
    "599 GTO",
    "599 SA APERTA",
    "612",
    "750",
    "812",
    "CALIFORNIA",
    "DAYTONA",
    "DINO GT4",
    "ENZO FERRARI",
    "F12",
    "F355",
    "F40",
    "F430",
    "F50",
    "F8",
    "FF",
    "GTC4LUSSO",
    "LAFERRARI",
    "MONDIAL",
    "MONZA",
    "PORTOFINO",
    "PUROSANGUE",
    "ROMA",
    "SF90",
    "SUPERAMERICA",
    "TESTAROSSA",
  ],
  FIAT: [
    "124",
    "124 SPIDER",
    "126",
    "127",
    "130",
    "131",
    "500",
    "500C",
    "500E",
    "500L",
    "500L CROSS",
    "500L LIVING",
    "500L TREKKING",
    "500L URBAN",
    "500L WAGON",
    "500S",
    "500X",
    "600",
    "600E",
    "ALBEA",
    "BARCHETTA",
    "BRAVA",
    "BRAVO",
    "CINQUECENTO",
    "COUPE",
    "CROMA",
    "DINO",
    "DOBLO",
    "DUCATO",
    "FIORINO",
    "FREEMONT",
    "FULLBACK",
    "GRANDE PANDA",
    "GRANDE PUNTO",
    "IDEA",
    "LINEA",
    "MAREA",
    "MARENGO",
    "MULTIPLA",
    "NEW PANDA",
    "PALIO",
    "PANDA",
    "PUNTO",
    "PUNTO EVO",
    "QUBO",
    "REGATA",
    "RITMO",
    "SCUDO",
    "SEDICI",
    "SEICENTO",
    "SIENA",
    "SPIDER EUROPA",
    "STILO",
    "STRADA",
    "TALENTO",
    "TEMPRA",
    "TIPO",
    "TOPOLINO",
    "ULYSSE",
    "UNO",
    "X 1/9",
  ],
  GENESIS: ["G70", "G80", "G90", "GV60", "GV70", "GV80"],
  HONDA: [
    "ACCORD",
    "AERODECK",
    "CITY",
    "CIVIC",
    "CLARITY",
    "CONCERTO",
    "CR-V",
    "CRX",
    "CR-Z",
    "E",
    "E:NY1",
    "ELEMENT",
    "FR-V",
    "HR-V",
    "INSIGHT",
    "INTEGRA",
    "JAZZ",
    "LEGEND",
    "LOGO",
    "NSX",
    "ODYSSEY",
    "PILOT",
    "PRELUDE",
    "RIDGELINE",
    "S2000",
    "SHUTTLE",
    "STREAM",
    "ZR-V",
  ],
  HYUNDAI: [
    "ACCENT",
    "ATOS",
    "AZERA",
    "BAYON",
    "COUPE",
    "ELANTRA",
    "EXCEL",
    "GALLOPER",
    "GENESIS",
    "GETZ",
    "GRANDEUR",
    "GRAND SANTA FE",
    "H-1",
    "H 100",
    "H-1 STAREX",
    "H 200",
    "H350",
    "I10",
    "I20",
    "I30",
    "I40",
    "INSTER",
    "IONIQ",
    "IONIQ 5",
    "IONIQ 6",
    "IONIQ 9",
    "IX20",
    "IX35",
    "IX55",
    "KONA",
    "KONA ELEKTRO",
    "LANTRA",
    "MATRIX",
    "NEXO",
    "PONY",
    "SANTA FE",
    "SANTAMO",
    "S-COUPE",
    "SONATA",
    "STARIA",
    "TERRACAN",
    "TRAJET",
    "TUCSON",
    "VELOSTER",
    "VERACRUZ",
    "XG 30",
    "XG 350",
  ],
  INFINITI: [
    "EX",
    "FX",
    "G",
    "I",
    "JX",
    "M",
    "Q",
    "Q30",
    "Q40",
    "Q45",
    "Q50",
    "Q60",
    "Q70",
    "QX30",
    "QX4",
    "QX50",
    "QX56",
    "QX60",
    "QX70",
    "QX80",
  ],
  ISUZU: ["CAMPO", "D-MAX", "GEMINI", "MIDI", "PICK UP", "TROOPER"],
  IVECO: ["MASSIF"],
  JAC: ["8 PRO"],
  JAGUAR: [
    "DAIMLER",
    "E-PACE",
    "E-TYPE",
    "F-PACE",
    "F-TYPE",
    "I-PACE",
    "MK II",
    "S-TYPE",
    "XE",
    "XF",
    "XJ",
    "XJ12",
    "XJ40",
    "XJ6",
    "XJ8",
    "XJR",
    "XJS",
    "XJSC",
    "XK",
    "XK8",
    "XKR",
    "X-TYPE",
  ],
  JEEP: [
    "AVENGER",
    "CHEROKEE",
    "CJ",
    "COMANCHE",
    "COMMANDER",
    "COMPASS",
    "GLADIATOR",
    "GRAND CHEROKEE",
    "PATRIOT",
    "RENEGADE",
    "WAGONEER",
    "WILLYS",
    "WRANGLER",
  ],
  KGM: [
    "ACTYON",
    "KORANDO",
    "MUSSO",
    "MUSSO GRAND",
    "REXTON",
    "TIVOLI",
    "TORRES",
    "TORRES EVX",
  ],
  KIA: [
    "BESTA",
    "BORREGO",
    "CARENS",
    "CARNIVAL",
    "CEED",
    "CERATO",
    "CLARUS",
    "EV3",
    "EV6",
    "EV9",
    "JOICE",
    "K2500",
    "K2700",
    "LEO",
    "MAGENTIS",
    "MENTOR",
    "MINI",
    "NIRO",
    "NIRO EV",
    "OPIRUS",
    "OPTIMA",
    "PICANTO",
    "PREGO",
    "PRIDE",
    "PROCEED",
    "RETONA",
    "RIO",
    "ROADSTER",
    "ROCSTA",
    "SEPHIA",
    "SHUMA",
    "SORENTO",
    "SOUL",
    "SPORTAGE",
    "STINGER",
    "STONIC",
    "VENGA",
    "XCEED",
  ],
  KOENIGSEGG: ["AGERA", "CCR", "CCXR"],
  KTM: ["X-BOW"],
  LAMBORGHINI: [
    "AVENTADOR",
    "COUNTACH",
    "DIABLO",
    "ESPADA",
    "GALLARDO",
    "HURACÁN",
    "JALPA",
    "LM",
    "MIURA",
    "MURCIÉLAGO",
    "REVUELTO",
    "URRACO",
    "URUS",
  ],
  "LAND-ROVER": [
    "DEFENDER",
    "DISCOVERY",
    "DISCOVERY SPORT",
    "FREELANDER",
    "RANGE ROVER",
    "RANGE ROVER EVOQUE",
    "RANGE ROVER SPORT",
    "RANGE ROVER VELAR",
    "SERIES I",
    "SERIES II",
    "SERIES III",
  ],
  LEXUS: [
    "CT 200H",
    "LBX",
    "LC 500",
    "LFA",
    "LM",
    "RZ",
    "SC 400",
    "SC 430",
    "UX",
    "ES SERIES",
    "GS SERIES",
    "GX SERIES",
    "IS SERIES",
    "LS SERIES",
    "LX SERIES",
    "NX SERIES",
    "RC SERIES",
    "RX SERIES",
  ],
  LOTUS: [
    "340 R",
    "CORTINA",
    "ELAN",
    "ELETRE",
    "ELISE",
    "ELITE",
    "EMEYA",
    "EMIRA",
    "ESPRIT",
    "EUROPA",
    "EVORA",
    "EXCEL",
    "EXIGE",
    "SUPER SEVEN",
  ],
  MASERATI: [
    "222",
    "224",
    "228",
    "3200",
    "418",
    "420",
    "4200",
    "422",
    "424",
    "430",
    "BITURBO",
    "GHIBLI",
    "GRANCABRIO",
    "GRANSPORT",
    "GRANTURISMO",
    "GRECALE",
    "INDY",
    "KARIF",
    "LEVANTE",
    "MC12",
    "MC20",
    "MERAK",
    "QUATTROPORTE",
    "SHAMAL",
    "SPYDER",
  ],
  MAXUS: [
    "DELIVER 9",
    "EDELIVER 3",
    "EDELIVER 9",
    "EUNIQ 5",
    "EUNIQ 6",
    "MIFA 9",
    "T90",
  ],
  MAZDA: [
    "121",
    "2",
    "2 HYBRID",
    "3",
    "323",
    "5",
    "6",
    "6E",
    "929",
    "BONGO",
    "B SERIES",
    "BT-50",
    "CX-3",
    "CX-30",
    "CX-5",
    "CX-60",
    "CX-7",
    "CX-80",
    "CX-9",
    "DEMIO",
    "E SERIES",
    "MILLENIA",
    "MPV",
    "MX-3",
    "MX-30",
    "MX-5",
    "MX-6",
    "PREMACY",
    "PROTEGE",
    "RX-6",
    "RX-7",
    "RX-8",
    "TRIBUTE",
    "XEDOS",
  ],
  MCLAREN: [
    "540C",
    "570GT",
    "570S",
    "600LT",
    "620R",
    "650S",
    "650S COUPÉ",
    "650S SPIDER",
    "675LT",
    "675LT SPIDER",
    "720S",
    "750S",
    "765",
    "765LT",
    "ARTURA",
    "ELVA",
    "GT",
    "MP4-12C",
    "P1",
    "SENNA GTR",
    "SPEEDTAIL",
  ],
  MG: [
    "CYBERSTER",
    "EHS",
    "HS",
    "MARVEL R",
    "MG3",
    "MG4",
    "MG5",
    "MGA",
    "MGB",
    "MGF",
    "MIDGET",
    "MONTEGO",
    "S5",
    "TD",
    "TF",
    "ZR",
    "ZS",
    "ZT",
  ],
  MINI: [
    "ACEMAN",
    "CLUBVAN",
    "CABRIO SERIES (ALL)",
    "COOPER CABRIO",
    "COOPER D CABRIO",
    "COOPER S CABRIO",
    "COOPER SD CABRIO",
    "JOHN COOPER WORKS CABRIO",
    "ONE CABRIO",
    "CLUBMAN SERIES (ALL)",
    "COOPER CLUBMAN",
    "COOPER D CLUBMAN",
    "COOPER S CLUBMAN",
    "COOPER SD CLUBMAN",
    "JOHN COOPER WORKS CLUBMAN",
    "ONE CLUBMAN",
    "ONE D CLUBMAN",
    "COUNTRYMAN SERIES (ALL)",
    "COOPER C COUNTRYMAN",
    "COOPER COUNTRYMAN",
    "COOPER D COUNTRYMAN",
    "COOPER E COUNTRYMAN",
    "COOPER S COUNTRYMAN",
    "COOPER SD COUNTRYMAN",
    "COOPER SE COUNTRYMAN",
    "JOHN COOPER WORKS COUNTRYMAN",
    "ONE COUNTRYMAN",
    "ONE D COUNTRYMAN",
    "COUPE SERIES (ALL)",
    "COOPER COUPÉ",
    "COOPER S COUPÉ",
    "COOPER SD COUPÉ",
    "JOHN COOPER WORKS COUPÉ",
    "MINI (ALL)",
    "1000",
    "1300",
    "COOPER",
    "COOPER C",
    "COOPER D",
    "COOPER E",
    "COOPER S",
    "COOPER SD",
    "COOPER SE",
    "JOHN COOPER WORKS",
    "ONE",
    "ONE D",
    "ONE FIRST",
    "PACEMAN SERIES (ALL)",
    "COOPER D PACEMAN",
    "COOPER PACEMAN",
    "COOPER SD PACEMAN",
    "COOPER S PACEMAN",
    "JOHN COOPER WORKS PACEMAN",
    "ROADSTER SERIES (ALL)",
    "COOPER ROADSTER",
    "COOPER SD ROADSTER",
    "COOPER S ROADSTER",
    "JOHN COOPER WORKS ROADSTER",
  ],
  MITSUBISHI: [
    "3000 GT",
    "ASX",
    "CANTER",
    "CARISMA",
    "COLT",
    "CORDIA",
    "COSMOS",
    "DIAMANTE",
    "ECLIPSE",
    "ECLIPSE CROSS",
    "GALANT",
    "GALLOPER",
    "GRANDIS",
    "I-MIEV",
    "L200",
    "L300",
    "L400",
    "LANCER",
    "MIRAGE",
    "MONTERO",
    "OUTLANDER",
    "PAJERO",
    "PAJERO PININ",
    "PICK-UP",
    "PLUG-IN HYBRID OUTLANDER",
    "SANTAMO",
    "SAPPORO",
    "SIGMA",
    "SPACE GEAR",
    "SPACE RUNNER",
    "SPACE STAR",
    "SPACE WAGON",
    "STARION",
    "TREDIA",
  ],
  NISSAN: [
    "100 NX",
    "200 SX",
    "240 SX",
    "280 ZX",
    "300 ZX",
    "350Z",
    "370Z",
    "ALMERA",
    "ALMERA TINO",
    "ALTIMA",
    "ARIYA",
    "ARMADA",
    "BLUEBIRD",
    "CABSTAR",
    "CARGO",
    "CHERRY",
    "CUBE",
    "E-NV200",
    "EVALIA",
    "FRONTIER",
    "GT-R",
    "INTERSTAR",
    "JUKE",
    "KING CAB",
    "KUBISTAR",
    "LAUREL",
    "LEAF",
    "MAXIMA",
    "MICRA",
    "MURANO",
    "NAVARA",
    "NOTE",
    "NP 300",
    "NV200",
    "NV250",
    "NV300",
    "NV400",
    "PATHFINDER",
    "PATROL",
    "PICKUP",
    "PIXO",
    "PRAIRIE",
    "PRIMASTAR",
    "PRIMERA",
    "PULSAR",
    "QASHQAI",
    "QASHQAI+2",
    "QUEST",
    "SENTRA",
    "SERENA",
    "SILVIA",
    "SKYLINE",
    "SUNNY",
    "TERRANO",
    "TIIDA",
    "TITAN",
    "TOWNSTAR",
    "TRADE",
    "URVAN",
    "VANETTE",
    "X-TRAIL",
  ],
  PEUGEOT: [
    "1007",
    "104",
    "106",
    "107",
    "108",
    "2008",
    "204",
    "205",
    "206",
    "207",
    "208",
    "3008",
    "301",
    "304",
    "305",
    "306",
    "307",
    "308",
    "309",
    "4007",
    "4008",
    "404",
    "405",
    "406",
    "407",
    "408",
    "5008",
    "504",
    "505",
    "508",
    "604",
    "605",
    "607",
    "806",
    "807",
    "BIPPER",
    "BIPPER TEPEE",
    "BOXER",
    "E-208",
    "E-RIFTER",
    "E-TRAVELLER",
    "EXPERT",
    "EXPERT TEPEE",
    "ION",
    "J5",
    "PARTNER",
    "PARTNER TEPEE",
    "RCZ",
    "RIFTER",
    "TEPEE",
    "TRAVELLER",
  ],
  "ROLLS-ROYCE": [
    "CORNICHE",
    "CULLINAN",
    "DAWN",
    "FLYING SPUR",
    "GHOST",
    "PARK WARD",
    "PHANTOM",
    "SILVER CLOUD",
    "SILVER DAWN",
    "SILVER SERAPH",
    "SILVER SHADOW",
    "SILVER SPIRIT",
    "SILVER SPUR",
    "SPECTRE",
    "WRAITH",
  ],
  RENAULT: [
    "ALASKAN",
    "ALPINE A110",
    "ALPINE A310",
    "ALPINE V6",
    "ARKANA",
    "AUSTRAL",
    "AVANTIME",
    "CAPTUR",
    "CLIO",
    "COUPE",
    "ESPACE",
    "EXPRESS",
    "FLUENCE",
    "FUEGO",
    "GRAND ESPACE",
    "GRAND KANGOO",
    "GRAND KANGOO E-TECH",
    "GRAND MODUS",
    "GRAND SCENIC",
    "KADJAR",
    "KANGOO",
    "KANGOO E-TECH",
    "KOLEOS",
    "LAGUNA",
    "LATITUDE",
    "MASCOTT",
    "MASTER",
    "MEGANE",
    "MEGANE E-TECH",
    "MODUS",
    "P 1400",
    "R 11",
    "R 14",
    "R 18",
    "R 19",
    "R 20",
    "R 21",
    "R 25",
    "R 30",
    "R 4",
    "R 5",
    "R 6",
    "R 9",
    "RAFALE",
    "RAPID",
    "SAFRANE",
    "SCENIC",
    "SCENIC E-TECH",
    "SPIDER",
    "SYMBIOZ",
    "TALISMAN",
    "TRAFIC",
    "TWINGO",
    "TWIZY",
    "VEL SATIS",
    "WIND",
    "ZOE",
  ],
  SEAT: [
    "ALHAMBRA",
    "ALTEA",
    "ARONA",
    "AROSA",
    "ATECA",
    "CORDOBA",
    "EXEO",
    "IBIZA",
    "INCA",
    "LEON",
    "MALAGA",
    "MARBELLA",
    "MII",
    "TARRACO",
    "TERRA",
    "TOLEDO",
  ],
  SUBARU: [
    "B9 TRIBECA",
    "BAJA",
    "BRZ",
    "CROSSTREK",
    "FORESTER",
    "IMPREZA",
    "JUSTY",
    "LEGACY",
    "LEVORG",
    "LIBERO",
    "OUTBACK",
    "SOLTERRA",
    "SVX",
    "TREZIA",
    "TRIBECA",
    "VIVIO",
    "WRX STI",
    "XT",
    "XV",
  ],
  SUZUKI: [
    "(SX4) S-CROSS",
    "ACROSS",
    "ALTO",
    "BALENO",
    "CAPPUCCINO",
    "CARRY",
    "CELERIO",
    "GRAND VITARA",
    "IGNIS",
    "IK-2",
    "JIMNY",
    "KIZASHI",
    "LIANA",
    "LJ",
    "SJ SAMURAI",
    "SPLASH",
    "SUPER-CARRY",
    "SWACE",
    "SWIFT",
    "SX4",
    "VITARA",
    "WAGON R+",
    "X-90",
  ],
  TESLA: ["MODEL 3", "MODEL S", "MODEL X", "MODEL Y", "ROADSTER"],
  XPENG: ["G6", "G9", "P7"],
};
