import {
  BodyType,
  Brand,
  Color,
  DriveType,
  EnergyEfficiency,
  EquipmentItem,
  EuroNorm,
  FuelType,
} from "../catalog/index.mjs";

export const EQUIPMENT: Map<EquipmentItem, string> = new Map([
  ["360 DEGREE CAMERA", "360-Grad-Kamera"],
  ["7 SEATER", "7-Sitzer"],
  ["7 SEATS", "7 Sitze"],
  ["ADAPTIVE AIR SUSPENSION", "Adaptive Luftfederung"],
  ["ADAPTIVE CRUISE CONTROL", "Adaptiver Tempomat"],
  ["ADJUSTABLE STEERING WHEEL", "Verstellbares Lenkrad"],
  ["AIR CONDITIONING 3 ZONE", "3-Zonen-Klimaautomatik"],
  ["AIR CONDITIONING 4 ZONE", "4-Zonen-Klimaautomatik"],
  ["AIR QUALITY SYSTEM", "Luftgütesystem"],
  ["ALL WHEEL DRIVE", "Allradantrieb"],
  ["ALLWHEEL DRIVE", "Allradantrieb"],
  ["ANDROID AUTO", "Android Auto"],
  ["AUDI APPLICATION STORE", "Audi App Store"],
  ["AUDI CONNECT REMOTE & CONTROL", "Audi Connect Remote & Control"],
  ["AUDI PRE SENSE FRONT", "Audi Pre Sense Front"],
  ["AUDI PRE SENSE REAR PACKAGE", "Audi Pre Sense Heckpaket"],
  ["AUDI VIRTUAL COCKPIT PLUS", "Audi Virtual Cockpit Plus"],
  ["AUTO HOLD", "Auto Hold-Funktion"],
  ["AUTOMAT", "Automatik"],
  ["AUTOMATIC HIGH BEAM", "Fernlichtassistent"],
  ["BANG AND OLUFSEN SOUND SYSTEM", "Bang & Olufsen Soundsystem"],
  ["BLACK ROOF", "Schwarzes Dach"],
  ["COLLISION WARNING SYSTEM", "Kollisionswarnsystem"],
  ["DEACTIVABLE PASSANGER AIRBAG", "Deaktivierbarer Beifahrerairbag"],
  ["DRIVER ASSISTANCE", "Fahrerassistenz"],
  ["ELECTRIC DRIVER SEAT WITH MEMORY", "Elektrischer Fahrersitz mit Memory"],
  ["ELECTRIC HEATER", "Elektrische Heizung"],
  [
    "ELECTRICALLY FOLDING REAR HEADRESTS",
    "Elektrisch klappbare Kopfstützen hinten",
  ],
  ["EXTERIOR SPEAKERS", "Außenlautsprecher"],
  ["FRONT AND REAR SENSORS", "Sensoren vorne und hinten"],
  ["FRONT SENSORS", "Sensoren vorne"],
  ["FULL BODY PAINT", "Volllackierung"],
  ["HARMAN/KARDON", "Harman/Kardon"],
  ["HEAD RESTRAINTS", "Kopfstützen"],
  ["HEAT PUMP", "Wärmepumpe"],
  ["HEATED WINDSHIELD", "Beheizte Windschutzscheibe"],
  ["LANE DEPARTURE ASSIST", "Spurhalteassistent"],
  ["LEASABLE WITH VAT", ""],
  ["LEATHER UPHOLSTERY", "Lederausstattung"],
  ["M SPORT STEERING WHEEL", "M Sportlenkrad"],
  ["M SPORT SUSPENSION", "M Sportfahrwerk"],
  ["MATRIX LED HEADLIGHTS", "Matrix LED-Scheinwerfer"],
  ["MERIDIAN SOUND SYSTEM", "Meridian Soundsystem"],
  ["METTALIC PAINT", "Metallic-Lackierung"],
  ["NEWLY SERVICED", "Neu gewartet"],
  ["ORREFORS GEAR SHIFTER", "Orrefors Schaltknauf"],
  ["PACKAGE: AMG", "AMG-Paket"],
  ["PACKAGE: BLACK OPTICS PACKAGE", "Black Optics Paket"],
  ["PACKAGE: EXECUTIVE", "Executive-Paket"],
  ["PACKAGE: EXTENDED BLACK OPTICS PACKAGE", "Erweitertes Black Optics Paket"],
  ["PACKAGE: NIGHT PACKAGE", "Night-Paket"],
  ["PACKAGE: PREMIUM PACKAGE", "Premium-Paket"],
  ["PACKAGE: QUATTRO EDITION", "quattro Edition"],
  ["PACKAGE: R DESIGN", "R-Design-Paket"],
  ["PACKAGE: R LINE", "R-Line-Paket"],
  ["PACKAGE: R LINE EXTERIOR", "R-Line Exterieur"],
  [
    "PACKAGE: RS SPORT CHASSI WITH DYNAMIC RIDE",
    "RS Sportfahrwerk mit Dynamic Ride",
  ],
  ["PACKAGE: RS SPORT EXHAUST SYSTEM", "RS Sportabgasanlage"],
  ["PACKAGE: S LINE", "S line"],
  ["PACKAGE: S LINE INTERIOR", "S line Interieur"],
  ["PACKAGE: ST LINE", "ST-Line"],
  ["PACKAGE: STYLE", "Style-Paket"],
  ["PACKAGE: TECHNICAL PACKAGE", "Technik-Paket"],
  ["PACKAGE: WINTER PACKAGE", "Winter-Paket"],
  ["PANEL LIGHTING", "Ambientebeleuchtung"],
  ["PANO", "Panoramadach"],
  ["PARKING HEATER", "Standheizung"],
  ["PEDALS IN STAINLESS STEEL", "Edelstahlpedale"],
  ["PEDESTRIAN DETECTION", "Fußgängererkennung"],
  ["PEUGEOT CONNECT", "Peugeot Connect"],
  ["PIXEL LED HEADLIGHTS", "Pixel LED-Scheinwerfer"],
  ["PROGRESSIVE POWER STEERING", "Progressive Lenkung"],
  ["RAIN SENSOR", "Regensensor"],
  ["READYTODRIVE NOTIFICATION", "Ready-to-Drive Benachrichtigung"],
  ["REAR CAMERA", "Rückfahrkamera"],
  ["REAR SENSORS", "Sensoren hinten"],
  ["RED BRAKE CALIPERS", "Rote Bremssättel"],
  ["RED EXTERIOR COLOR", "Rote Außenfarbe"],
  ["RUBBER MATS", "Gummimatten"],
  ["SEAT HEATING (FRONT)", "Sitzheizung vorne"],
  ["SEAT HEATING (REAR)", "Sitzheizung hinten"],
  ["SEAT VENTILATION (FRONT)", "Sitzbelüftung vorne"],
  ["SENSOR (FRONT AND REAR)", "Sensoren vorne und hinten"],
  ["SENSOR (FRONT)", "Sensoren vorne"],
  ["SENSOR (REAR)", "Sensoren hinten"],
  ["SENSORS (FRONT AND REAR)", "Sensoren vorne und hinten"],
  ["SENSORS (FRONT)", "Sensoren vorne"],
  ["SIDE ASSIST", "Spurwechselassistent"],
  ["SIGNAGE SCANNING", "Verkehrszeichenerkennung"],
  ["SMARPHONE INTERFACE", "Smartphone-Schnittstelle"],
  ["SOFT CLOSE", "Soft-Close"],
  ["SOUND SYSTEM", "Soundsystem"],
  ["STEERING WHEEL KNOBS", "Lenkradtasten"],
  ["SUMMER AND WINTER WHEELS", "Sommer- und Winterräder"],
  ["TECH PLUS", "Tech Plus"],
  ["TOW HOOK", "Anhängerkupplung"],
  ["TRAFFIC SIGN RECOGNITION", "Verkehrszeichenerkennung"],
  ["TRAILER ASSIST", "Anhängerassistent"],
  [
    "UPHOLSTERY (BLACK LEATHERETTE AND FABRIC)",
    "Polsterung (Schwarzes Kunstleder und Stoff)",
  ],
  ["UPHOLSTERY (LEATHER AND ALCANATARA)", "Polsterung (Leder und Alcantara)"],
  ["UPHOLSTERY (LEATHER AND FABRIC)", "Polsterung (Leder und Stoff)"],
  [
    "UPHOLSTERY (VALCONA LEATHER WITH DIAMOND QUILTING)",
    "Polsterung (Valcona-Leder mit Rautensteppung)",
  ],
  [
    "UPHOLSTERY PREMIUM FABRIC AND SUEDE",
    "Polsterung Premium Stoff und Wildleder",
  ],
  [
    "UPHOLSTERY: (VALCONA LEATHER WITH DIAMOND QUILTING)",
    "Polsterung (Valcona-Leder mit Rautensteppung)",
  ],
  ["VOICE CONTROL", "Sprachsteuerung"],
  ["WINTER WHEELS", "Winterräder"],
  ["WIRELESS PHONE CHARGER", "Kabelloses Laden"],
]);

export const BODY_TYPE: Map<BodyType, string> = new Map([
  ["SUV", "SUV"],
  ["HATCHBACK", "Limousine"],
  ["COMBI", "Kombi"],
  ["SEDAN", "Limousine"],
  ["COMMERCIAL VEHICLE", "Kasten"],
  ["MINI VAN", "Andere"],
  ["COUPE", "Coupé"],
  ["CABRIOLET", "Cabrio"],
]);

export const FUEL_TYPE: Map<FuelType, string> = new Map([
  ["BENZIN", "Benzin"],
  ["DIESEL", "Diesel"],
  ["HYBRID", "Hybrid"],
  ["ELECTRIC", "Elektro"],
  ["BENZIN/ETHANOL", "Benzin"],
  ["NATURAL GAS", "Gas"],
  ["BENZIN/NATURAL GAS", "Benzin"],
]);

export const DRIVE_TYPE: Map<DriveType, string> = new Map([
  ["2WHEELDRIVE", "Zweiradantrieb"],
  ["ALLWHEELDRIVE", "Allrad"],
]);

export const TRANSMISSION_TYPE: Map<string, string> = new Map([
  ["AUTOMATIC", "Automatik"],
  ["MANUAL", "Manuell"],
]);

export const COLOR: Map<Color, string> = new Map([
  ["WHITE", "Weiß"],
  ["BLACK", "Schwarz"],
  ["GRAY", "Grau"],
  ["SILVER", "Silber"],
  ["BLUE", "Blau"],
  ["RED", "Rot"],
  ["GREEN", "Grün"],
  ["BROWN", "Braun"],
  ["PURPLE", "Lila"],
  ["ORANGE", "Orange"],
]);

export const BRAND: Map<Brand, string> = new Map([
  ["AUDI", "AUDI"],
  ["VOLKSWAGEN", "VOLKSWAGEN"],
  ["VOLVO", "VOLVO"],
  ["TOYOTA", "TOYOTA"],
  ["MERCEDES-BENZ", "MERCEDES-BENZ"],
  ["BMW", "BMW"],
  ["KIA", "KIA"],
  ["CITROEN", "CITROËN"],
  ["SKODA", "SKODA"],
  ["OPEL", "OPEL"],
  ["FORD", "FORD"],
  ["JAGUAR", "JAGUAR"],
  ["HYUNDAI", "HYUNDAI"],
  ["MAZDA", "MAZDA"],
  ["RENAULT", "RENAULT"],
  ["PEUGEOT", "PEUGEOT"],
  ["CUPRA", "CUPRA"],
  ["MG", "MG"],
  ["ALFA ROMEO", "ALFA ROMEO"],
  ["SEAT", "SEAT"],
  ["FIAT", "FIAT"],
  ["SUZUKI", "SUZUKI"],
  ["LEXUS", "LEXUS"],
  ["LYNK-AND-CO", "LYNK & CO"],
  ["SUBARU", "SUBARU"],
  ["MITSUBISHI", "MITSUBISHI"],
  ["CHEVROLET", "CHEVROLET"],
  ["MINI", "MINI"],
  ["SAAB", "SAAB"],
  ["TESLA", "TESLA"],
  ["NISSAN", "NISSAN"],
  ["DACIA", "DACIA"],
  ["PORSCHE", "PORSCHE"],
  ["LAND ROVER", "LAND ROVER"],
]);

export const ENERGY_EFFICIENCY: Map<EnergyEfficiency, string> = new Map([
  ["A", "a"],
  ["B", "b"],
  ["C", "c"],
  ["D", "d"],
  ["E", "e"],
  ["F", "f"],
  ["G", "g"],
]);

export const EURO_NORM: Map<EuroNorm, string> = new Map([
  ["EURO 6", "Euro 6"],
  ["EURO 5", "Euro 5"],
  ["EURO 4", "Euro 4"],
]);
